### ISSUE TITLE
IOS7でログイン時にナビゲーションバーが透明になる

### ISSUE THREAD

**Issue by nasust** [hatena/Hatena-Bookmark-iOS-SDK#54]
![screenshot 2013 10 06 08 29 21](https://f.cloud.github.com/assets/5146712/1275869/ff5779ac-2e15-11e3-8d59-68c2396c5140.png)

IOS7でログイン時にナビゲーションバーが透明になってしまいます。
barStyleを変更してみたんですが、何故か変更されません。

**Comment by yashigani** [comment]
@nasust 問題は解決されましたでしょうか？
