### ISSUE TITLE
はてなの認証が時々切れて再ログインが必要になる

### ISSUE THREAD

**Issue by naoya** [hatena/Hatena-Bookmark-iOS-SDK#60]
SDK を組み込んだアプリ (HBFav2) のユーザーから報告が上がっているのですが、表題の現象が起こるようです。
- https://github.com/naoya/HBFav2/issues/82

ひとによって発生頻度が違っていて
- 全く発生しないユーザー (当方がこれ)
- 希に発生するユーザー
- 一日一度の頻度くらいで頻繁に発生するユーザー

とがいるようです。

issue の中でもコメントしていますが、はてなの認証は、当方のアプリでは HTBHatenaBookmarkViewController.alloc.init でコントローラを起動して、以降の処理は完全に SDK 側に任せているため、おそらくですが、SDK もしくはサーバーサイドに原因があるのではないか、と思っています。

ただし、当方が利用しているのが RubyMotion なので、(可能性は低いものの) Objective-C で書いた場合との互換性の部分に差があって何か問題が起こっていることも否定はできません。

**Comment by yashigani** [comment]
解決されていそうなのでcloseします https://github.com/naoya/HBFav2/issues/112
