### ISSUE TITLE
一瞬前回のソーシャルボタン状況が見える 

### ISSUE THREAD

**Issue by Nyoho** [hatena/Hatena-Bookmark-iOS-SDK#64]
ブックマークするビューで「追加」を押したときに、閉じていく瞬間に「直前の」ソーシャルボタンのON/OFF状況が見えることがあります。

再現例
1. 前回 Twitter に共有するようにしてブックマークを追加していた。(鳥さんアイコンのみカラー表示)
2. 次の別のブックマークをするときに、Twitter共有は外して、「追加」をする。
3. すると、Twitter共有は外したはずなのに、「前回の」状態のTwitter共有がカラー表示になった状態のボタンたちが見えて閉じられる。(Twitter共有はされていない)

このようにすると手元では再現します。
毎回「あれっ? 共有にしたままだっけ」と思ってどきっとし、Twitterに流れているか確認することがあるので、できれば正常な表示になるととてもありがたく存じます。

**Comment by yashigani** [comment]
@Nyoho v1.3で修正したものを取り込みました。SDKのアップデートをお願いします。
