### ISSUE TITLE
ATS (App Transfer Security) を有効にすると機能しない

### ISSUE THREAD

**Issue by sawat** [hatena/Hatena-Bookmark-iOS-SDK#66]
ATSを有効にするとATSの警告アラートが複数回表示され、ブックマークの登録や閲覧ができません。
内部で使用しているAPIがHTTPでしか利用できないのだと思いますが、対応していただけるとありがたいです。
Exception Domains に hatena.ne.jp（サブドメイン含む）を追加して、NSExceptionAllowsInsecureHTTPLoads を許可すれば使用できることは確認しております。

![2016-12-22 10 33 38](https://cloud.githubusercontent.com/assets/454870/21412441/b86ccc98-c833-11e6-9fc1-6aa1ff2b583b.png)

**Comment by yashigani** [comment]
開発ブログで告知いたしましたように、はてなブックマークREST APIのhttps化はロードマップに含まれておりますので、API側の対応をお待ちいただけますでしょうか。
具体的な日付は決まっておりませんので、対応されるまでは除外設定でご利用いただけますと幸いです。

http://bookmark.hatenastaff.com/entry/2017/01/12/123000
