### ISSUE TITLE
iOS 自定义导航栏如何实现？

### ISSUE THREAD

**Issue by KexingWestRoad** [hatena/Hatena-Bookmark-iOS-SDK#69]
- (instancetype)initWithNavigationBarClass:(nullable Class)navigationBarClass toolbarClass:(nullable Class)toolbarClass
这个方法提供了自定义导航栏的方法，但是我尝试去实现navigationBarClass的时候，发现在iPhone X上面状态栏没法覆盖到，Apple不是推崇这种方式去完全自定义导航栏吗？

**Comment by nakiwo** [comment]
Thank you for your feedback.
However this SDK is no longer supported. Sorry for the inconvenience. 
For further details about this deprecation, please refer the article below.

http://bookmark.hatenastaff.com/entry/2017/01/12/123000
